### PR TITLE
Add JWT verification and use JWT with SMD

### PR DESCRIPTION
**Pull request by synackd**
Add functionality in BSS to:

- Verify if SMD has authentication enabled
- Validate its own JWT to see if it needs to fetch a new one (and fetch it)
  - Right now validation is simply that the JWT hasn't expired and is after the nbf field
- Present a valid JWT when requesting SMD protected endpoints

Also:

- Add Triad license

### CODE REVIEW

**Comment by synackd** [comment]
REMINDER: Get rid of auth token print statement before merging.

**Comment by synackd** [comment]
@davidallendj Could you take a look?

Even when presenting a valid JWT to SMD, it still responds with 401.

**Comment by davidallendj** [comment]
Are you getting a "token is unauthorized" error?

**Comment by synackd** [comment]
Yes. Looks like it works intermittently though.

**Comment by davidallendj** [comment]
Which branch of the deployment recipes are you using?

**Comment by synackd** [comment]
I'm on [this](https://github.com/synackd/deployment-recipes/tree/separate-auth-noauth-tests) branch with the following additions in the BSS environment in `ochami-services.yml`:

```
BSS_OAUTH2_PUBLIC_BASE_URL=http://hydra:4444
BSS_OAUTH2_ADMIN_BASE_URL=http://hydra:4445
```

**EDIT:** I also added `hydra` to the BSS `depends_on` list.

**Comment by synackd** [comment]
@davidallendj Can you review this?

**Review by davidallendj — APPROVED** [review]

**Pull request merged**
